version: "3.9"

services:      
  db:
    container_name: db
    image: mysql/mysql-server:5.6.31
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "somepass"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "someuser"
      MYSQL_PASSWORD: "somepass"
      MYSQL_HOST: "localhost"
    volumes:
      - ./datadir:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d   
      
  webapp:
    image: webdevops/php-apache:ubuntu-12.04
    environment:
      WEB_DOCUMENT_INDEX: "index.html"
      PHP_DISPLAY_ERRORS: "0"
    volumes:
      - ./php-app:/app
    ports:
      - 127.0.0.1:8090:80


